### ISSUE TITLE
/var/lib/pbench-agent does not exist after RPM installation

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2674] opened 2022-03-10 15:39 UTC
pbench-agent-0.71.0-14g4cbc95439.noarch
pbench-trafficgen commit 47d4fe5575c94b949c4db8c5cf8d6b5c148c56bc (HEAD -> master, origin/master, origin/HEAD)
trex v2.87

pbench-register-tool-set
[ERROR] pbench run directory, /var/lib/pbench-agent, does not exist

Mkdir /var/lib/pbench-agent workarounds this

**Comment by aokuliar-rh** [comment] 2022-03-10 15:39
This seems to be problem only with RHEL9

**Comment by webbnh** [comment] 2022-03-11 20:47
Hi Adam, sorry you hit this.  This is a duplicate of #2665, and it is, AFAIK, new with v0.71 and not limited to RHEL9.

**Closed by webbnh** 2022-03-11 20:47 UTC
Labels: bug, help wanted, Agent, tools
