### ISSUE TITLE
Bug with passing patterns in pidstat tool

### ISSUE THREAD

**Issue by vikaslaad** [distributed-system-analysis/pbench#232] opened 2016-05-05 20:32 UTC
I tried to use pidstat tool and wanted to monitor only openshift and docker processes. here is the command I used to register tool

pbench-register-tool --name=pidstat --remote=$host -- --interval=3600 --patterns=openshift,docker

When I login to remote and see the pbench files under reference-result directory I see following content in pidstat-stderr.txt

docker: '3600' is not a docker command.
See 'docker --help'.

No data is collected in pidstat-stdout.txt.

**Comment by portante** [comment] 2016-05-31 21:34
@atheurer, @ndokos, can one of you review this issue?  This is languishing... :(

**Comment by ndokos** [comment] 2016-06-01 21:57
This seems to be caused by incorrect quoting of the patterns in the pidstat tool. A proposed fix has been submitted as PR #251.

**Closed** 2016-09-20 19:32 UTC
Labels: bug
