### ISSUE TITLE
`pbench-register-tool-trigger` reports no triggers found without any options

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2268] opened 2021-04-30 09:24 UTC
pbench-agent-0.69.7:

```
$ pbench-register-tool-trigger
No __triggers__ in /var/lib/pbench-agent/tools-default
```

**Comment by portante** [comment] 2021-05-04 00:08
I suspect this is intended behavior.  There were no triggers provided, and at the end it just reported what was already registered.

Seems like we should report an error if no triggers were given.

**Comment by ndokos** [comment] 2021-05-21 15:25
Fixed by #2319.

**Closed by ndokos** 2021-05-21 15:25 UTC
Labels: Agent, QE feedback, bug, tools
