### ISSUE TITLE
Ansible role for enabling the optional repo (rhel-*-server-optional-rpms) for rhel users.

### ISSUE THREAD

**Issue by tenstormavi** [distributed-system-analysis/pbench#862] opened 2018-08-01 05:04 UTC
Currently, there are no ansible roles present to enable the rhel optional server repo. This is required for installation of some packages like perl-switch etc while installing pbench-agent.

**Comment by ndokos** [comment] 2018-08-01 16:25
I think the problem is more general. I'll close this issue and open a new one.

**Closed by ndokos** 2018-08-01 16:25 UTC
Labels: Agent
