### ISSUE TITLE
pbench-fio depends on python-pandas but does not install it until runtime

### ISSUE THREAD

**Issue by jtaleric** [distributed-system-analysis/pbench#716] opened 2017-11-09 12:45 UTC
pbench-fio installs without python-pandas, however at runtime, python-pandas is required. Either install python-pandas when the user installs pbench-fio, or have use/need of python-pandas be optional, and defaulted to disabled.

**Comment by bengland2** [comment] 2017-11-13 13:15
it's weirder than that on my current system, which is a RHEL75 build:

```
[root@perf146 ~]# pbench-fio --targets=/dev/pmem0,/dev/pmem1,/dev/pmem2,/dev/pmem3 --samples=3 -b 5 --direct=1 --runtime=30 --file-size=64000
Could not install pandas package

[root@perf146 ~]# yum install pandas
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
No package pandas available.
Error: Nothing to do

[root@perf146 ~]# yum search pandas
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
============================================================================ N/S matched: pandas ============================================================================
python-pandas.x86_64 : Python library providing high-performance data analysis tools

[root@perf146 ~]# yum install python-pandas
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Package python-pandas-0.17.1-1.el7.x86_64 already installed and latest version
Nothing to do

[root@perf146 ~]# uname -a
Linux perf146.perf.lab.eng.bos.redhat.com 3.10.0-693.12.1.el7.x86_64 #1 SMP Mon Nov 6 10:54:56 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

[root@perf146 ~]# rpm -qa | grep redhat
redhat-release-server-7.5-0.12.el7.x86_64
```

**Comment by bengland2** [comment] 2017-11-14 20:51
root cause of problem is that there is no pbench-agent.cfg file installed by default, and this is what tells pbench-fio what RPM name is to install pandas.  See /opt/pbench-agent/config/pbench-agent.cfg.example, it has two different values for "pandas-package" under [packages] section, one for RHEL and one for Fedora.  This seems wrong - it should know which distro it is on and customize accordingly.  I worked around it by doing

```
# cd /opt/pbench-agent/config
# cp pbench-agent.cfg.example pbench-agent.cfg
```

and deleting the assignment of this variable for Fedora, leaving the assignment for RHEL.  Now pbench-fio gets farther.

**Comment by ndokos** [comment] 2017-11-15 18:59
How are you installing? If you install the pbench-agent  "internal" RPM, there should be a `pbench-agent.cfg` file and it should have one `pandas-package` line (the correct one for the distro).

**Comment by jtaleric** [comment] 2017-11-15 19:53
Yes, I am installing the internal RPM.

**Comment by bengland2** [comment] 2017-11-15 21:48
My point is that some people inside of Red Hat might want to use Fedora, and conversely, some people outside of Red Hat might want to use RHEL/centos.  It just doesn't make sense to fix this problem in this way.  BTW, I use linode.com sometimes and that's outside redhat and I can't use pbench-agent-internal then, there I would need to run pbench-fio on centos, which presumably would be the same as RHEL.  So I need this to work there as well.  Same for amazon EC2, where RHEL AMI images are present but you can't use pbench-agent-internal.

Seems to me like instead of pbench-agent-internal, we should have a pbench-westford-server RPM that drops in /opt/pbench/id_rsa and points pbench-move-results to the pbench.perf.lab.eng.bos.redhat.com, and that's ALL it does, so there is only 1 pbench-agent RPM.

**Comment by ndokos** [comment] 2017-11-16 03:59
There *is* only one pbench-agent RPM. It contains all the environment-independent bits required to run pbench - the same RPM is used in Westford, in EC2, in various testing environments or in the scale lab (or anywhere else). But you still run in an environment and you need environment-specific bits (a config file and a key file) to run: that's exactly what the pbench-agent-internal RPM contains. Of course, different environments will require different environment-specific bits and therefore different pbench-agent-internal RPMs (or some other package format - RPMs are convenient but certainly not necessary). So I'm not sure whether we are in violent agreement or whether you are proposing something different. If the latter, maybe it'll be easier to hash it out f2f and then write up an issue.

**Comment by ndokos** [comment] 2017-11-17 22:24
The pbench-fio RPM on COPR now explicitly depends on the appropriate pandas package (python-pandas on RHEL/CentOS, python2-pandas on Fedora). I had to bump the release number, so when you install pbench-fio you should be looking for version 2.14-2.

The problem that @bengland2 reported in the second note above is related: it had to do with the incorrect way I built the "internal" RPMs. That made the installed config file specify a pandas package of `python2-pandas` even on RHEL/CentOS systems, where there is no such package. The "internal" RPMs for all current environments have been rebuilt to DTRT. Although now that pbench-fio will be installing the pandas package anyway, this fix is not strictly necessary: belt added to suspenders.

**Comment by ndokos** [comment] 2017-11-17 22:25
Closing this. Please reopen if there are problems.

**Closed by ndokos** 2017-11-17 22:25 UTC
