### ISSUE TITLE
`pbench-trafficgen --traffic-generator=trex-txrx-profile` crashes with exception

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2391] opened 2021-07-28 09:57 UTC
* `pbench-agent` 0.69.8
* `pbench-trafficgen` commit `6cbf23632367e92b0ba4acbca9ecfd06919dd18f`

```
pbench-trafficgen --devices 0000:06:00.0,0000:06:00.1  --config=Test  --skip-git-pull --traffic-generator=trex-txrx-profile

[2021-07-15 10:01:56.639425][BSO] EXCEPTION: Traceback (most recent call last):
[2021-07-15 10:01:56.639425][BSO]   File "/opt/trafficgen/trex_tg_lib.py", line 594, in load_traffic_profile
[2021-07-15 10:01:56.639425][BSO]     profile = json.load(traffic_profile_fp)
[2021-07-15 10:01:56.639425][BSO]   File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
[2021-07-15 10:01:56.639425][BSO]     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
[2021-07-15 10:01:56.639425][BSO]   File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
[2021-07-15 10:01:56.639425][BSO]     return _default_decoder.decode(s)
[2021-07-15 10:01:56.639425][BSO]   File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
[2021-07-15 10:01:56.639425][BSO]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2021-07-15 10:01:56.639425][BSO]   File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
[2021-07-15 10:01:56.639425][BSO]     raise JSONDecodeError("Expecting value", s, err.value) from None
[2021-07-15 10:01:56.639425][BSO] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2021-07-15 10:01:56.639425][BSO]
[2021-07-15 10:01:56.639428][BSO] ERROR: Could not load a valid traffic profile from /var/lib/pbench-agent/trafficgen_Test_tg:trex-profile_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2021-07-15T08:01:04/1-none-bidirectional-64B-1024flows-0.002pct_drop/traffic-profile.json
[error][2021-07-15T08:01:57.701247749] iteration 1-none-bidirectional-64B-1024flows-0.002pct_drop sample 1 returned non-zero exit code, 1
[error][2021-07-15T08:01:57.820119241] Aborting benchmark
```

**Comment by webbnh** [comment] 2022-02-07 20:09
@aokuliar-rh, are you able to reproduce this with the current (i.e., v0.71) version of the Pbench Agent?

If so, I'll want to look at the `traffic-profile.json` that the diagnostics are referring to...could you attach that to this issue?

Thanks!

**Comment by webbnh** [comment] 2022-02-14 20:46
This appears to be a duplicate of #2265.  Let's track this issue there.

**Closed by webbnh** 2022-02-14 20:46 UTC
Labels: bug, Agent, trafficgen
