### ISSUE TITLE
pbench-fio doubles up on arguments in fio cmdline

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#331] opened 2016-08-15 18:13 UTC
e.g.,  the command line assembled by pbench-fio was ...

/usr/local/bin/fio --output-format=json /var/lib/pbench-agent/fio__2016-08-15_17:57:52/1-write-4KiB/sample1/fio.job  --client=vm1 --client=vm2 --max-jobs=2 --output-format=json /var/lib/pbench-agent/fio__2016-08-15_17:57:52/1-write-4KiB/sample1/fio.job

... but the --output-format and specifying the fio jobfile are doubled up. The --output-format argument can be  anywhere but the fio jobfile must be the last argument passed. Oddly, this does not prevent fio from running successfully in my test but I can't say that for every other combination of options.

**Comment by atheurer** [comment] 2016-08-15 18:42
I See where the problem is and will submit a PR shortly

**Comment by ndokos** [comment] 2016-08-15 22:16
Fixed by PR #334.

**Closed by ndokos** 2016-08-15 22:16 UTC
