### ISSUE TITLE
pbench-uperf fails to get client output files on error

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#326] opened 2016-08-12 20:44 UTC
```
[root@gprfc053 ~]# pbench-uperf -C test --clients=gprfc053.o.internal,gprfc054.o.internal,gprfc055.o.internal --servers=gprfc062.o.internal,gprfc063.o.internal,gprfc064.o.internal --test-type=stream -m 1048576 -p tcp -i 1 --samples=1
Warning: Permanently added 'gprfc062.o.internal,172.17.10.62' (ECDSA) to the list of known hosts.
Warning: Permanently added 'gprfc063.o.internal,172.17.10.63' (ECDSA) to the list of known hosts.
Warning: Permanently added 'gprfc064.o.internal,172.17.10.64' (ECDSA) to the list of known hosts.
Collecting system information
Starting iteration  (1 of 1)
test sample 1 of 1
client[gprfc053.o.internal]protocol[tcp]test[stream]instances[1]size[1048576] <-> server[gprfc062.o.internal]
client[gprfc054.o.internal]protocol[tcp]test[stream]instances[1]size[1048576] <-> server[gprfc063.o.internal]
client[gprfc055.o.internal]protocol[tcp]test[stream]instances[1]size[1048576] <-> server[gprfc064.o.internal]
scp: /var/lib/pbench-agent/uperf__2016-08-11_19:25:38/1-tcp_stream-1048576B-1i/sample1/client::gprfc053.o.internal-server::gprfc062.o.internal:21000--client_output.txt: No such file or directory
scp: /var/lib/pbench-agent/uperf__2016-08-11_19:25:38/1-tcp_stream-1048576B-1i/sample1/client::gprfc054.o.internal-server::gprfc063.o.internal:22000--client_output.txt: No such file or directory
scp: /var/lib/pbench-agent/uperf__2016-08-11_19:25:38/1-tcp_stream-1048576B-1i/sample1/client::gprfc055.o.internal-server::gprfc064.o.internal:23000--client_output.txt: No such file or directory
uperf-postprocess: could not find any result files to process, exiting
Can't open /var/lib/pbench-agent/uperf__2016-08-11_19:25:38/1-tcp_stream-1048576B-1i/sample1/result.json: No such file or directory at /opt/pbench-agent/bench-scripts/postprocess/process-iteration-samples line 174.
Iteration 1-tcp_stream-1048576B-1i complete (1 of 1), with 1 pass and 0 failures
generate-benchmark-summary: could not open file /var/lib/pbench-agent/uperf__2016-08-11_19:25:38/1-tcp_stream-1048576B-1i/result.json: No such file or directory
Collecting system information
```

The clients were not able to run because iptables was installed with rules which prevented it.  But the `uperf` output was not captured for some reason.

**Comment by atheurer** [comment] 2016-08-15 15:06
This is a duplicate of issue #321

**Closed by atheurer** 2016-08-15 15:06 UTC
