### ISSUE TITLE
Required pbench copr builds for Fedora 34 

### ISSUE THREAD

**Issue by pravins** [distributed-system-analysis/pbench#2357] opened 2021-06-15 15:47 UTC
Description:
I tried to install pbench-* on Fedora-34 today through the https://copr.fedorainfracloud.org/coprs/ndokos/pbench/. But got an error, since no builds are available for Fedora-34.
I am presently going ahead by changing baseurl  
baseurl=https://copr-be.cloud.fedoraproject.org/results/ndokos/pbench/fedora-33-x86_64/
Let me know, if i can help in anyway. 

Steps to Reproduce:
1. Install Fedora 34 : https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/34/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-34-1.2.iso
2. Download Copr Repo file from documentation:  https://github.com/distributed-system-analysis/pbench "How is it Installed?"
3. Copr Repo Build: https://copr.fedorainfracloud.org/coprs/ndokos/pbench/
4. $dnf install pbench-agent

Actual Issue:
Errors during downloading metadata for repository 'copr:copr.fedorainfracloud.org:ndokos:pbench':
  - Status code: 404 for https://download.copr.fedorainfracloud.org/results/ndokos/pbench/fedora-34-x86_64/repodata/repomd.xml (IP: 13.249.233.82)
Error: Failed to download metadata for repo 'copr:copr.fedorainfracloud.org:ndokos:pbench': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Expected:
pbench-agent should get installed.

Seems @ndokos own the repo

**Comment by ndokos** [comment] 2021-06-16 20:08
@pravins: I enabled the F34 x86_64 builds on both the copr-pbench and copr-pbench-test repos and rebuilt the 0.69.4 release on copr-pbench, so you should be all set. Let me know if there are problems. If not, I'll close this issue. Thanks!

**Comment by pravins** [comment] 2021-06-17 09:26
Thanks a lot @ndokos  for fixing this. Now, no need to do any changes in gitrepo.
Other problem:
failed: [192.168.122.18] (item=pbench-sysstat) => {"ansible_loop_var": "item", "changed": false, "failures": ["No package pbench-sysstat available."], "item": "pbench-sysstat", "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

I see one available in copr repo is only for F32: https://copr.fedorainfracloud.org/coprs/ndokos/pbench/build/1378718/

Since, it was failing my ansible-playbook, i install pbench-systat package manually from https://copr.fedorainfracloud.org/coprs/portante/pbench/build/1877822/  Since it seems more latest. 

But after successful install, i am getting following issues:

$pbench-register-tool --name=vmstat

**Comment by pravins** [comment] 2021-06-17 11:31
I tried to install pbench-server:
TASK [pbench-server-install : ensure the pbench-server RPM is installed] *********************************************************************************************************************
fatal: [192.168.122.152]: FAILED! => {"changed": false, "failures": ["No package pbench-server available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

We need pbench-server also for Fedora-34 https://copr-be.cloud.fedoraproject.org/results/ndokos/pbench/

**Comment by ndokos** [comment] 2021-06-23 02:49
OK - now built in CORP are: pbench-sysstat-12.0.3 and pbench-server-0.69.5.

The `sos report` error is unrelated and is caused by a recent change in `sos report` that breaks our sos report collection in the 0.69.4 agent. That is one of the fixes in the 0.69.8 agent, but for now that is only available in the COPR pbench-test repo. We are waiting for people to weigh in on this, but it is probably better to release it now and deal with any fallout, since the current version is causing problems in any case.

**Comment by pravins** [comment] 2021-06-23 03:36
Thanks @ndokos for the explanation. i will try to install above package from the copr and then will test 0.69.8 for sos report error. Thanks a lot.

**Comment by ndokos** [comment] 2021-06-23 19:26
The `sos report` issue is indeed unrelated to this, but an issue (#2363) nevertheless. Thanks @pravins and @riya-17 for finding and reporting it!

**Comment by portante** [comment] 2021-06-23 20:33
No changes needed for the code, except for the fix mentioned above, closing as `invalid` since none of this has to do with the code.

**Closed by portante** 2021-06-23 20:33 UTC
