### ISSUE TITLE
Pidstat data not available with containerized pbench-agent version 0.58-1gb64aef2b

### ISSUE THREAD

**Issue by wabouhamad** [distributed-system-analysis/pbench#1169] opened 2019-04-15 14:29 UTC
Pidstat cpu_usage, file_io, memory_usage and data are not being plotted, getting:

pidstat - cpu_usage
percent_cpu

No data from any series met set thresholds for graphing.

The CSV data has values of "0" in all the column

http://pbench.perf.lab.eng.bos.redhat.com/results/EC2::ip-172-31-12-183/nodevertical/pbench-user-benchmark__2019.04.11T19.51.40/1/sample1/tools-default/svt_node_1:ip-172-31-129-239.us-west-2.compute.internal/pidstat/

**Comment by ndokos** [comment] 2019-04-15 18:16
Duplicate of #1164 - let's use that one to track the underlying issue.

**Closed by ndokos** 2019-04-15 18:16 UTC
