### ISSUE TITLE
pbench-uperf where hosts are both clients and servers

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#327] opened 2016-08-15 12:55 UTC
I've been able to run pbench-uperf between a single pair of hosts but when I try to run a test where hosts act as both client and server I get this:

http://pastebin.test.redhat.com/402458

I need to do this to emulate Ceph's network behavior.  reverting to my own netperf scripts until I can sort out how to use this tool.

**Comment by ndokos** [comment] 2016-08-15 13:44
@bengland2, IIUC, a couple of people ran into this last week and @atheurer has a fix, but I'm not sure in what stage  it is. I can build a test RPM using his branch if necessary.

**Comment by atheurer** [comment] 2016-08-15 14:57
Nick, pull request is here:
https://github.com/distributed-system-analysis/pbench/pull/328

**Comment by atheurer** [comment] 2016-08-15 15:06
This is a duplicate of issue #321

**Comment by ndokos** [comment] 2016-08-15 22:15
Fixed by PR#328.

**Closed by ndokos** 2016-08-15 22:15 UTC
