### ISSUE TITLE
pbench-list-tools not finding the group members

### ISSUE THREAD

**Issue by zulcss** [distributed-system-analysis/pbench#1504] opened 2020-02-16 16:24 UTC
vagrant@workstation:~$ pbench-list-tools -n sar
/bin/ls: cannot access 'tools-iostat': No such file or directory
/bin/ls: cannot access 'tools-mpstat': No such file or directory
/bin/ls: cannot access 'tools-perf': No such file or directory
/bin/ls: cannot access 'tools-pidstat': No such file or directory
/bin/ls: cannot access 'tools-proc-interrupts': No such file or directory
/bin/ls: cannot access 'tools-proc-vmstat': No such file or directory
/bin/ls: cannot access 'tools-sar': No such file or directory
/bin/ls: cannot access 'tools-turbostat': No such file or directory
name: sar groups:

**Comment by webbnh** [comment] 2021-02-19 17:19
**Initial investigation**

This command works OK for me (although the command produces _no_ output...) using `quay.io/pbench/pbench-agent-all-fedora-32:v0.71.0-130`, so, presumably the issue here is related to something in the configuration.

However, if I mess around with the `-C` switch or the `_PBENCH__AGENT_CONFIG` environment variable, the code responds "ungracefully" (but doesn't produce the result above).

It would be helpful if there were command options which listed the tool names and group names which were available to be supplied to the `-n` and `-g` switches, and if those switches validated their options.  (I will look into adding these.)

(And, there's a typo in the help text for the `-C` switch:  `envrionment` ==> `environment`.)

**Comment by ndokos** [comment] 2021-09-15 03:31
This looks like a shell implementation of `pbench-list-tools` (note the `/bin/ls` invocations), so it cannot be 0.71. OTOH, I cannot reproduce it on 0.69.9 either. 

Closing.

**Closed by ndokos** 2021-09-15 03:31 UTC
Labels: bug, Agent, tools
