### ISSUE TITLE
Unable to register iostat, pidstat, mpstat, sar tools on OCP 4.x nodes when registering these tools with containerized pbench-agent version 0.58-1gb64aef2b

### ISSUE THREAD

**Issue by wabouhamad** [distributed-system-analysis/pbench#1168] opened 2019-04-11 16:23 UTC
I am also seeing [error][2019-04-11T13:23:29.596145376] [check_install_rpm] the installation of pbench-sysstat-11.2.0 failed

**Comment by ndokos** [comment] 2019-04-11 18:45
@wabouhamad: 0.58 uses pbench-sysstat version 12.0.3. You probably have to update your container to include that version. The RPM is available on COPR. Let me know if you have questions.

**Comment by chaitanyaenr** [comment] 2019-04-15 00:54
The pbench-agent image has been updated to include pbench-sysstat version 12.0.3. Thanks @ndokos.

**Comment by ndokos** [comment] 2019-04-15 05:29
@chaitanyaenr - thanks! @wabouhamad: please test and report whether the problem is resolved - thank you!

**Comment by wabouhamad** [comment] 2019-04-15 14:29
@ndokos tested with pbench-agent image that has the pbench-sysstat version 12.0.3, the tools are now registering fine but there are issues getting pidstat data, creating new issue:

https://github.com/distributed-system-analysis/pbench/issues/1169

**Comment by ndokos** [comment] 2019-04-17 18:13
OK - thanks! Closing this.

**Closed by ndokos** 2019-04-17 18:13 UTC
